WASdev/azure.websphere-traditional.singleserver

.github/workflows/package.yaml, .gitignore, README.md, pom.xml, src/main/arm/createUiDefinition.json, src/main/arm/mainTemplate.json, src/main/arm/parameters.json, src/main/cli/deploy.azcli, src/main/scripts/install.sh
This PR is to address the following issues:
* Resolve #4
* Resolve #5 
* ARM template for creating Azure VM, executing VM extension and other related resources
* Script to install tWAS base single server from the base image
* Script to check entitlement result and exit immediately for invalid user
* Workflow to set up cicd pipeline for packaging the repo
The following test cases are passed before sending out the PR:
* Successfully deploy a tWAS base single server on Azure VM with the entitled IBMid, and verified version 9.0.5.10 is installed
* `/datadrive/IBM/WebSphere/Base/V9/bin/versionInfo.sh` 
```
WVER0010I: Copyright (c) IBM Corporation 2002, 2012; All rights reserved.
WVER0012I: VersionInfo reporter version 1.15.1.48, dated 2/8/12 …
```
=> Solution template to deploy an IBM WebSphere Traditional 9.0.5.x Single server on Azure VM

src/main/arm/createUiDefinition.json
The PR is to update license link for tWAS base, related to #13 .
=> Update license link for tWAS base

pom.xml, src/main/arm/createUiDefinition.json, src/main/arm/mainTemplate.json, src/main/scripts/install.sh
The PR is to resolve the following issues:
* Resolve #8 
* Resolve #9 
* Apply content review comments
* Update image info for tWAS Base and tracking pid
The following test cases are tested and verified before opening the PR for review:
* The UI has been verified using the [Create UI Definition Sandbox](https://portal.azure.com/?feature.customPortal=false#blade/Microsoft_Azure_CreateUIDef/SandboxBlade)
* A VM with tWAS Base single server installed from the new published base image of tWAS Base, can be successfully deployed with Azure CLI
=> Update text and twas base image info

docs/howto-update-for-was-fixpack.md, docs/twas-solution-test-cases.md
The PR is to resolve #19 by adding two documentations:
* `docs/howto-update-for-was-fixpack.md`
* `docs/twas-solution-test-cases.md`
=> Docs for fix pack update and test case

pom.xml, src/main/arm/createUiDefinition.json
=> Update license text

pom.xml, src/main/arm/createUiDefinition.json, src/main/scripts/create-ds.sh, src/main/scripts/install.sh
The PR is to 
* Address UI review comments for the new feature about IBM Db2 database connection, details pls see https://github.com/WASdev/azure.websphere-traditional.singleserver/pull/49#issuecomment-1256371941.
* Resolve #51 Fix the issue that testing database connection failed, which is caused by the undesired substitution for db connection parameters during mvn build.
=> Revise wording and fix the issue that testing database connection failed

pom.xml, src/main/bicep/config.json
modified:   src/main/bicep/config.json
=> On branch edburns-msft-ibm-100 Update offer to use latest base images.

.github/workflows/integration-test.yaml, test/deploy-app.py.template, test/deploy-app.sh
The PR is to enhance the existing integration test pipeline by deploying a sample CRUD app [Azure-Samples/websphere-cafe](https://github.com/Azure-Samples/websphere-cafe).
See the successful workflow run [integration-test](https://github.com/majguo/azure.websphere-traditional.singleserver/actions/runs/4674718781).
=> Enhance the integration test pipeline to support app deployment

src/main/bicep/config.json
modified:   src/main/bicep/config.json
=> On branch edburns-msft-ibm-267-update-single-to-use-9.0.20230502

pom.xml
=> On branch edburns-msft-ibm-267-update-single-increment-pom

.github/workflows/package.yaml
Use the latest release [microsoft/microsoft-partner-center-github-action@v3](https://github.com/microsoft/microsoft-partner-center-github-action/releases/tag/v3) which requires offerId/planId as inputs.
=> Use microsoft-partner-center-github-action@v3

.github/workflows/package.yaml, docs/howto-update-for-was-fixpack.md
…
modified:   .github/workflows/package.yaml
=> On branch edburns-msft-ibm-342-end-to-end-automation-documentation Remove conditional restricting publishing to only when run within WASdev.

.github/workflows/integration-test.yaml, .github/workflows/package.yaml, .github/workflows/setup-credentials.sh, .github/workflows/tear-down-credentials.sh, README.md, docs/howto-update-for-was-fixpack.md, docs/twas-solution-test-cases.md, pom.xml, src/main/bicep/mainTemplate.bicep, src/main/bicep/modules/_pids/_empty.bicep, src/main/cli/deploy.azcli, src/main/resources/marketing-artifacts/partner-center.html, src/main/scripts/create-ds-db2.py.template, src/main/scripts/create-ds-oracle.py.template, src/main/scripts/create-ds-postgres.py.template, src/main/scripts/create-ds-sqlserver.py.template, src/main/scripts/create-ds.sh, src/main/scripts/install.sh, test/deploy-app.py.template, test/deploy-app.sh, test/install-db2.sh, test/install-oracle.sh
modified:   .github/workflows/integration-test.yaml
modified:   .github/workflows/package.yaml
modified:   .github/workflows/setup-credentials.sh
modified:   .github/workflows/tear-down-credentials.sh
modified:   README.md
modified:   docs/howto-update-for-was-fixpack.md
modified:   docs/twas-solution-test-cases.md
modified:   pom.xml
modified:   src/main/bicep/mainTemplate.bicep
modified:   src/main/bicep/modules/_pids/_empty.bicep
modified:   src/main/cli/deploy.azcli
modified:   src/main/resources/marketing-artifacts/partner-center.html
modified:   src/main/scripts/create-ds-db2.py.template
modified:   src/main/scripts/create-ds-oracle.py.template
modified:   src/main/scripts/create-ds-postgres.py.template
modified:   src/main/scripts/create-ds-sqlserver.py.template
modified: …
=> On branch edburns-msft-ibm-336-license-headers

docs/howto-update-for-was-fixpack.md
modified:   docs/howto-update-for-was-fixpack.md
=> On branch edburns-msft-ibm-398-explain-pids Reference pid doc.

src/main/bicep/mainTemplate.bicep
Use values from https://dev.azure.com/was-azure/was-azure/_workitems/edit/440#9268525
=> Update ApiVersion to the latest

pom.xml, src/main/bicep/config.json
For 9.0.5.17 update: https://github.com/WASdev/azure.websphere-traditional.singleserver/issues/89
=> 9.0.5.17 update

pom.xml, src/main/bicep/config.json
For https://github.com/WASdev/azure.websphere-traditional.singleserver/issues/93
=> Version update for 9.0.5.18

pom.xml, src/main/bicep/config.json
- https://github.com/WASdev/azure.websphere-traditional.singleserver/issues/93
- https://github.com/WASdev/azure.websphere-traditional.cluster/issues/234
=> Changes to this repo to fix the cross-repo spanning problems described in the following issues.

pom.xml, src/main/bicep/mainTemplate.bicep
Update  plan id (Pid) for the new [Single Server plan](https://partner.microsoft.com/en-us/dashboard/commercial-marketplace/offers/d287697e-d90f-485a-9fe0-c2f12676973d/plans/4390614a-634b-4be3-81c6-57ee63ef0f9a/technicalconfiguration) 
(pid-d287697e-d90f-485a-9fe0-c2f12676973d-partnercenter)
=> Update new Plan Id (pid) to Single Server offering

pom.xml
=> On branch edburns-msft-ibm-608-increment-pom

.github/workflows/integration-test.yaml, .github/workflows/package.yaml
This pull request includes several updates to the GitHub Actions workflows for integration testing and packaging. The changes enhance the flexibility and reliability of the workflows by introducing new parameters, updating resource deployment methods, and improving error handling.
Key changes include:
* Added a new `location` parameter to the `.github/workflows/integration-test.yaml` file to allow dynamic specification of Azure resource locations.
* Updated the `location` environment variable to use the new input parameter or default to 'eastus'.
* Changed the deployment method for PostgreSQL from `Azure Database for PostgreSQL` to `Azure Database for PostgreSQL Flexible Server` for better performance and flexibility.
* Improved the `curl` command in the integration test workflow to fail …
=> CICD pipeline enhancements

src/main/arm/parameters.json
modified:   src/main/arm/parameters.json
Missing double quotes.
=> On branch edburns/ibm-1218-resolve-problems-found-during-publishing

README.md, src/main/arm/parameters.json
Fix workflow failures due to incorrect JSON substitution.
=> Make the Integration tests run
